# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Messenger(object):
    def setupUi(self, Messenger):
        Messenger.setObjectName("Messenger")
        Messenger.resize(978, 529)
        self.contactView = QtWidgets.QListWidget(Messenger)
        self.contactView.setGeometry(QtCore.QRect(10, 100, 181, 381))
        self.contactView.setObjectName("contactView")
        self.inputEdit = QtWidgets.QLineEdit(Messenger)
        self.inputEdit.setGeometry(QtCore.QRect(200, 490, 671, 31))
        self.inputEdit.setObjectName("inputEdit")
        self.sendButton = QtWidgets.QPushButton(Messenger)
        self.sendButton.setGeometry(QtCore.QRect(880, 490, 89, 31))
        self.sendButton.setObjectName("sendButton")
        self.chatView = QtWidgets.QListWidget(Messenger)
        self.chatView.setGeometry(QtCore.QRect(200, 100, 761, 381))
        self.chatView.setObjectName("chatView")
        self.contactButton = QtWidgets.QPushButton(Messenger)
        self.contactButton.setGeometry(QtCore.QRect(10, 490, 181, 31))
        self.contactButton.setObjectName("contactButton")
        self.connectButton = QtWidgets.QPushButton(Messenger)
        self.connectButton.setGeometry(QtCore.QRect(530, 10, 121, 71))
        self.connectButton.setObjectName("connectButton")
        self.serverEdit = QtWidgets.QLineEdit(Messenger)
        self.serverEdit.setGeometry(QtCore.QRect(90, 10, 151, 25))
        self.serverEdit.setReadOnly(False)
        self.serverEdit.setObjectName("serverEdit")
        self.portEdit = QtWidgets.QLineEdit(Messenger)
        self.portEdit.setGeometry(QtCore.QRect(340, 10, 111, 25))
        self.portEdit.setObjectName("portEdit")
        self.label = QtWidgets.QLabel(Messenger)
        self.label.setGeometry(QtCore.QRect(40, 10, 51, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Messenger)
        self.label_2.setGeometry(QtCore.QRect(300, 10, 41, 17))
        self.label_2.setObjectName("label_2")
        self.accountEdit = QtWidgets.QLineEdit(Messenger)
        self.accountEdit.setGeometry(QtCore.QRect(90, 50, 151, 25))
        self.accountEdit.setObjectName("accountEdit")
        self.label_3 = QtWidgets.QLabel(Messenger)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Messenger)
        self.label_4.setGeometry(QtCore.QRect(260, 50, 67, 17))
        self.label_4.setObjectName("label_4")
        self.passwordEdit = QtWidgets.QLineEdit(Messenger)
        self.passwordEdit.setGeometry(QtCore.QRect(340, 50, 111, 25))
        self.passwordEdit.setObjectName("passwordEdit")
        self.checkBox = QtWidgets.QCheckBox(Messenger)
        self.checkBox.setGeometry(QtCore.QRect(460, 50, 92, 23))
        self.checkBox.setObjectName("checkBox")
        self.stateView = QtWidgets.QListWidget(Messenger)
        self.stateView.setGeometry(QtCore.QRect(670, 40, 291, 41))
        self.stateView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.stateView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.stateView.setObjectName("stateView")
        self.label_5 = QtWidgets.QLabel(Messenger)
        self.label_5.setGeometry(QtCore.QRect(670, 20, 67, 17))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Messenger)
        self.stateView.indexesMoved['QModelIndexList'].connect(self.stateView.scrollToBottom)
        QtCore.QMetaObject.connectSlotsByName(Messenger)
        Messenger.setTabOrder(self.serverEdit, self.portEdit)
        Messenger.setTabOrder(self.portEdit, self.accountEdit)
        Messenger.setTabOrder(self.accountEdit, self.passwordEdit)
        Messenger.setTabOrder(self.passwordEdit, self.checkBox)
        Messenger.setTabOrder(self.checkBox, self.connectButton)
        Messenger.setTabOrder(self.connectButton, self.contactView)
        Messenger.setTabOrder(self.contactView, self.contactButton)
        Messenger.setTabOrder(self.contactButton, self.inputEdit)
        Messenger.setTabOrder(self.inputEdit, self.sendButton)
        Messenger.setTabOrder(self.sendButton, self.chatView)

    def retranslateUi(self, Messenger):
        _translate = QtCore.QCoreApplication.translate
        Messenger.setWindowTitle(_translate("Messenger", "Messenger"))
        self.sendButton.setText(_translate("Messenger", "Send"))
        self.contactButton.setText(_translate("Messenger", "Add contact"))
        self.connectButton.setText(_translate("Messenger", "Connect"))
        self.label.setText(_translate("Messenger", "Server"))
        self.label_2.setText(_translate("Messenger", "Port"))
        self.label_3.setText(_translate("Messenger", "Account"))
        self.label_4.setText(_translate("Messenger", "Password"))
        self.checkBox.setText(_translate("Messenger", "Guest"))
        self.label_5.setText(_translate("Messenger", "Status"))

